version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    restart: always

  webserver:
    build:
      context: .
      dockerfile: docker/dockfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always